#####
# Documentation
# Redwood: https://render.com/docs/deploy-redwood
# YAML (all config values): https://render.com/docs/yaml-spec
#####

services:
- name: example-blog-web
  type: web
  env: static
  buildCommand: yarn rw deploy render web
  staticPublishPath: ./web/dist
  envVars:
  - key: NODE_VERSION
    value: 14
  routes:
  - type: rewrite
    source: /.redwood/functions/*
    destination: https://example-blog-api-dnd9.onrender.com/*
  - type: rewrite
    source: /*
    destination: /index.html

- name: example-blog-api
  type: web
  env: node
  region: oregon
  buildCommand: yarn && yarn rw build api
  startCommand: yarn rw deploy render api
  envVars:
  - key: NODE_VERSION
    value: 14
  - key: DATABASE_URL
    value: postgresql://augustina:uJjWdXhvx7@pg-db-provision.cm0mkpwj8arx.eu-central-1.rds.amazonaws.com:5432/purple_elephant
  disk:
    name: sqlite-data
    mountPath: /opt/render/project/src/api/db/data
    sizeGB: 1
